---
name: 'Update Dependencies'
on:
  workflow_dispatch:
  schedule:
    # every Monday
    - cron: '0 0 * * 1'
env:
  GOPROXY: https://proxy.golang.org
permissions:
  contents: read
jobs:
  update-deps:
    if: ${{ github.repository == 'kubernetes/cloud-provider-aws' }}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: go.mod
      - name: Update Dependencies
        id: update_deps
        run: |
          make update-deps
          echo 'changes<<EOF' >> $GITHUB_OUTPUT
          git status --porcelain >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          title: 'Update dependencies'
          commit-message: Update dependencies
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          branch: dependencies/update
          branch-suffix: timestamp
          base: master
          delete-branch: true
          labels: |
            ok-to-test
            release-note-none
          body: |
            Updating go.mod with latest dependencies.
